# Generated by Django 5.0.8 on 2025-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationcode',
            name='sdu_share_e_email_b88240_idx',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('register', '注册'), ('login', '登录'), ('delete', '注销'), ('reset', '重置密码')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
