# Generated by Django 5.0.8 on 2025-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0002_remove_emailverificationcode_sdu_share_e_email_b88240_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
