# Generated by Django 5.0.8 on 2025-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0003_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_access_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
