# Generated by Django 5.0.8 on 2025-02-13 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sdu_share', '0005_blocklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('block', models.BooleanField(db_index=True, default=False, verbose_name='是否屏蔽')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('origin_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='原文链接')),
                ('resource_link', models.CharField(max_length=255, verbose_name='资源URL')),
                ('article_summary', models.CharField(max_length=255, verbose_name='文章简介')),
                ('cover_link', models.CharField(max_length=255, verbose_name='封面URL')),
                ('article_type', models.CharField(choices=[('original', '原创'), ('repost', '转载')], default='original', max_length=10, verbose_name='文章类型')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('tags', models.ManyToManyField(related_name='articles', to='sdu_share.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-publish_time'],
                'indexes': [models.Index(fields=['-publish_time'], name='sdu_share_a_publish_25d968_idx')],
            },
        ),
    ]
