# Generated by Django 5.0.8 on 2025-02-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0007_alter_like_options_like_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_summary',
            field=models.CharField(blank=True, default='这个人没有写简介...', max_length=255, null=True, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='resource_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='资源URL'),
        ),
    ]
