# Generated by Django 5.0.8 on 2025-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0008_alter_article_article_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_link',
            field=models.CharField(blank=True, default='后续改成默认封面？或者检查到空就不加载', max_length=255, null=True, verbose_name='封面URL'),
        ),
    ]
