# Generated by Django 5.0.8 on 2025-02-13 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0009_alter_article_cover_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_index=True, max_length=255, verbose_name='课程名称')),
                ('course_type', models.CharField(choices=[('compulsory', '必修课'), ('elective', '选修课'), ('restricted_elective', '限选课')], db_index=True, max_length=50, verbose_name='课程类型')),
                ('college', models.CharField(max_length=255, verbose_name='开设学院')),
                ('credits', models.DecimalField(decimal_places=2, help_text='例如：3.50 学分', max_digits=4, verbose_name='学分')),
                ('course_teacher', models.CharField(max_length=255, verbose_name='授课教师')),
                ('course_method', models.CharField(choices=[('online', '线上'), ('offline', '线下'), ('hybrid', '混合')], db_index=True, max_length=50, verbose_name='教学方式')),
                ('assessment_method', models.TextField(verbose_name='考核方式')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('relative_articles', models.ManyToManyField(blank=True, related_name='courses', to='sdu_share.article', verbose_name='关联文章')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], decimal_places=2, max_digits=3, verbose_name='评分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评论')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sdu_share.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程评价',
                'verbose_name_plural': '课程评价',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='帖子ID')),
                ('post_title', models.CharField(db_index=True, help_text='标题最多255个字符', max_length=255, verbose_name='帖子标题')),
                ('content', models.TextField(help_text='支持Markdown格式', verbose_name='内容')),
                ('views', models.PositiveIntegerField(default=0, help_text='通过原子操作更新', verbose_name='浏览量')),
                ('block', models.BooleanField(db_index=True, default=False, verbose_name='是否屏蔽')),
                ('top', models.BooleanField(db_index=True, default=False, verbose_name='是否置顶')),
                ('publish_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发布时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='sdu_share.article', verbose_name='关联文章')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='sdu_share.course', verbose_name='关联课程')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='发帖人')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-publish_time'],
                'get_latest_by': 'publish_time',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='回复ID')),
                ('reply_content', models.TextField(help_text='回复内容最多支持5000字符', verbose_name='回复内容')),
                ('reply_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='回复时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='sdu_share.post', verbose_name='关联帖子')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='回复用户')),
            ],
            options={
                'verbose_name': '帖子回复',
                'verbose_name_plural': '帖子回复',
                'ordering': ['-reply_time'],
                'get_latest_by': 'reply_time',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name', 'college'], name='sdu_share_c_course__c3ce41_idx'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-publish_time'], name='sdu_share_c_course__027e45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['top', '-publish_time'], name='sdu_share_p_top_37417b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['poster', '-publish_time'], name='sdu_share_p_poster__b734d4_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['post', '-reply_time'], name='sdu_share_r_post_id_27cbe3_idx'),
        ),
    ]
