# Generated by Django 5.0.8 on 2025-02-13 19:19

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sdu_share', '0010_course_coursereview_post_reply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='收藏夹名称')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认收藏夹')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cover', models.URLField(blank=True, null=True, verbose_name='封面图URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sdu_share.starfolder', verbose_name='父级收藏夹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_folders', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='收藏备注')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='sdu_share.starfolder', verbose_name='所属收藏夹')),
            ],
            options={
                'verbose_name': '收藏记录',
                'verbose_name_plural': '收藏记录',
            },
        ),
        migrations.AddIndex(
            model_name='starfolder',
            index=models.Index(fields=['user', 'is_default'], name='sdu_share_s_user_id_e673b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='starfolder',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['content_type', 'object_id'], name='sdu_share_s_content_8339a7_idx'),
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['-created_at'], name='sdu_share_s_created_b95742_idx'),
        ),
        migrations.AddConstraint(
            model_name='star',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'folder'), name='unique_star_per_folder'),
        ),
    ]
