# Generated by Django 5.0.8 on 2025-02-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0011_starfolder_star_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='标签名'),
        ),
    ]
