# Generated by Django 5.0.8 on 2025-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0012_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hot_score',
            field=models.FloatField(db_index=True, default=0.0, editable=False, help_text='计算公式：浏览量×0.3 + 点赞数×0.7', verbose_name='热度分'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['article', '-publish_time'], name='sdu_share_p_article_20d718_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['course', '-publish_time'], name='sdu_share_p_course__7f6bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-views'], name='sdu_share_p_views_4b568c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-hot_score'], name='sdu_share_p_hot_sco_a795f8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish_time', 'block'], name='sdu_share_p_publish_aa3b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-hot_score', '-publish_time'], name='sdu_share_p_hot_sco_e88605_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['block', '-hot_score'], name='sdu_share_p_block_33819f_idx'),
        ),
    ]
