# Generated by Django 5.0.8 on 2025-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0013_post_hot_score_post_sdu_share_p_article_20d718_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['replier', '-reply_time'], name='sdu_share_r_replier_05364a_idx'),
        ),
    ]
