# Generated by Django 5.0.8 on 2025-02-26 13:48

import django.core.validators
import django.db.models.deletion
import sdu_share.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0014_reply_sdu_share_r_replier_05364a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sdu_share.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='图片文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(editable=False)),
                ('content_type', models.CharField(editable=False, max_length=50)),
                ('is_article_image', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['email', 'purpose'], name='email_purpose_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['expires_at'], name='expiry_idx'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['user', '-created_at'], name='sdu_share_i_user_id_680113_idx'),
        ),
    ]
