# Generated by Django 5.0.8 on 2025-02-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0015_image_emailverificationcode_email_purpose_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='sdu_share_i_user_id_680113_idx',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='is_article_image',
            new_name='is_profile_image',
        ),
    ]
