# Generated by Django 5.0.8 on 2025-02-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0016_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-reply_time'], 'verbose_name': '帖子回复', 'verbose_name_plural': '帖子回复'},
        ),
        migrations.RemoveIndex(
            model_name='reply',
            name='sdu_share_r_post_id_27cbe3_idx',
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sdu_share.reply', verbose_name='父级回复'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['post', 'parent_reply', '-reply_time'], name='sdu_share_r_post_id_7f0c12_idx'),
        ),
    ]
