# Generated by Django 5.0.8 on 2025-02-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sdu_share', '0017_alter_reply_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_type', models.CharField(choices=[('reply_post', '回复帖子'), ('reply_article', '回复文章'), ('reply_reply', '回复评论'), ('like', '点赞'), ('system', '系统通知'), ('message', '私信')], db_index=True, max_length=20, verbose_name='通知类型')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='已读状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='sdu_share_n_user_id_7e6367_idx'), models.Index(fields=['user', 'n_type'], name='sdu_share_n_user_id_0cba96_idx')],
            },
        ),
    ]
