# Generated by Django 5.0.8 on 2025-03-01 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0019_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='star',
            name='unique_star_per_folder',
        ),
        migrations.RemoveIndex(
            model_name='star',
            name='sdu_share_s_content_8339a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='starfolder',
            name='sdu_share_s_user_id_e673b1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='starfolder',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='star',
            name='object_id',
        ),
        migrations.AddField(
            model_name='star',
            name='content_id',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='内容ID'),
        ),
        migrations.AlterField(
            model_name='star',
            name='content_type',
            field=models.CharField(choices=[('course', '课程'), ('article', '文章'), ('post', '帖子')], db_index=True, max_length=20, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='star',
            name='notes',
            field=models.TextField(blank=True, help_text='不超过500个字符', max_length=500, null=True, verbose_name='收藏备注'),
        ),
        migrations.AlterField(
            model_name='starfolder',
            name='cover',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='封面图URL'),
        ),
        migrations.AlterField(
            model_name='starfolder',
            name='description',
            field=models.TextField(blank=True, help_text='不超过500个字符', max_length=500, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='starfolder',
            name='is_default',
            field=models.BooleanField(default=False, help_text='每个用户有且只有一个默认收藏夹', verbose_name='默认收藏夹'),
        ),
        migrations.AlterField(
            model_name='starfolder',
            name='name',
            field=models.CharField(help_text='不超过100个字符', max_length=100, verbose_name='收藏夹名称'),
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['content_type', 'content_id'], name='sdu_share_s_content_bb3a50_idx'),
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['user', 'folder'], name='sdu_share_s_user_id_6aa5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='starfolder',
            index=models.Index(fields=['user', 'parent'], name='sdu_share_s_user_id_a23b59_idx'),
        ),
        migrations.AddConstraint(
            model_name='star',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'content_id', 'folder'), name='unique_star_per_folder'),
        ),
        migrations.AddConstraint(
            model_name='starfolder',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_folder_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='starfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_folder'),
        ),
    ]
