# Generated by Django 5.0.8 on 2025-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_share', '0020_remove_star_unique_star_per_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='content_type',
            field=models.SmallIntegerField(choices=[(0, '课程'), (1, '文章'), (2, '帖子')], db_index=True, verbose_name='内容类型'),
        ),
    ]
